name: 'Automatic version updates'

on:
  schedule:
    # minute hour dom month dow (UTC)
    - cron: '00 15 * * *'
  # enable manual trigger of version updates
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: zosopentools/duckdbport/action@main
        with:
          files: buildenv
        env:
          GITHUB_TOKEN: ${{ secrets.BUMP_TOKEN }}
